---
- name: make gitlab yum directory
  file:
    path: /var/www/html/gitlab
    state: directory
    recurse: yes

- name: download gitlab repo script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
    dest: /usr/local/bin/script.rpm.sh
    owner: root
    mode: 0755

- name: run the repo script
  command: /usr/local/bin/script.rpm.sh

- name: sync the repo
  command: reposync -n -r "gitlab_gitlab-ce" -p "/var/www/html/gitlab"

- name: initialize the yum repo
  command: createrepo --database "/var/www/html/gitlab"