---
- hosts: tag_instance_role_bastion
  connection: ssh
  gather_facts: no
  become: true
  pre_tasks:
    - meta: refresh_inventory
  roles:
    - ansible-yum
    - ansible-vnc
    - ansible-registry