---
- hosts: tag_instance_role_bastion
  connection: ssh
  gather_facts: no
  become: true
  pre_tasks:
    - meta: refresh_inventory
  roles:
    - ansible-yum
    - ansible-vnc
    - ansible-registry
  post_tasks:
    - name: copy ssh config file
      copy:
        src: ./config
        dest: /home/ec2-user/.ssh/config
        owner: ec2-user
        mode: 0600